services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Brizy\Bundle\EntitiesBundle\:
    resource: '../../../src/*'
    exclude: '../../../src/{DependencyInjection,Resources,Entity,BrizyEntitiesBundle.php}'
    public: true


  Brizy\Bundle\EntitiesBundle\EventListener\UserSubscriber:
    tags:
      - { name: 'doctrine.event_subscriber' }
